In [5]:
import numpy as np

In [13]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
a.shape

(19,)

In [10]:
a[0]

0

In [11]:
a[3]

3

In [16]:
a=a.reshape(2,10)
a.shape

(2, 10)

In [17]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
a[0,3]

3

In [25]:
a=a.reshape(2,5,2)

In [26]:
a.shape

(2, 5, 2)

In [27]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [28]:
a[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
a[0,3]

array([6, 7])

In [30]:
a[0,3,1]

7

In [36]:
b=np.arange(0,40,2).reshape(4,5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [37]:
a_python_list = [2**x for x in range(10)]

In [38]:
c=np.array(a_python_list)
c

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [40]:
zero_array=np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
one_array=np.ones(10)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
empty_array=np.empty(100)
empty_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
lucky_array=np.full((5,5),13)
lucky_array

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [45]:
diagonal_array=np.eye(5,5)
diagonal_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
random_array=np.random.random(10)
random_array

array([0.43463916, 0.71977222, 0.34167073, 0.61395803, 0.74115284,
       0.17784872, 0.91712799, 0.21520868, 0.98380444, 0.22968486])

In [47]:
linspace_array=np.linspace(100,200,5)
linspace_array

array([100., 125., 150., 175., 200.])