In [1]:
import numpy as np

In [2]:
arr = np.arange(5,30,2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [3]:
boolArr = arr<10
boolArr

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [4]:
arr[boolArr]

array([5, 7, 9])

In [5]:
arr[arr<20]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
arr[arr%3==0]

array([ 9, 15, 21, 27])

In [12]:
arr[(arr>10) & (arr<20)]

array([11, 13, 15, 17, 19])

In [14]:
arr=np.arange(24).reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
arr[0]

array([0, 1, 2, 3, 4, 5])

In [16]:
arr[0,1]

1

In [17]:
arr[0,2:3]

array([2])

In [18]:
arr[0,2:4]

array([2, 3])

In [19]:
arr[0,:]

array([0, 1, 2, 3, 4, 5])

In [20]:
arr[:,1]

array([ 1,  7, 13, 19])

In [21]:
arr[:1,1]

array([1])

In [22]:
arr[:1,1:2]

array([[1]])

In [23]:
arr[:,-1]

array([ 5, 11, 17, 23])

In [24]:
arr[:,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [27]:
arr=np.arange(50).reshape(10,5)
split_level=0.2
num_rows=arr.shape[0]
split_border=round(split_level*num_rows)

In [31]:
arr[:split_border,:]

array([[15, 16, 17, 18, 19],
       [35, 36, 37, 38, 39]])

In [32]:
arr[split_border:,:]

array([[30, 31, 32, 33, 34],
       [45, 46, 47, 48, 49],
       [40, 41, 42, 43, 44],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29]])

In [30]:
np.random.shuffle(arr)

In [33]:
X_learn = arr[split_border:,:-1]
X_test = arr[:split_border,:-1]
y_learn = arr[split_border:,-1]
y_test = arr[:split_border,-1]

In [36]:
data=np.arange(500).reshape(100,5)
split_level=0.2
num_rows=data.shape[0]
split_border=round(split_level*num_rows)

In [41]:
np.random.shuffle(data)

In [42]:
X_learn = data[split_border:,:-1]
X_test = data[:split_border,:-1]
y_learn = data[split_border:,-1]
y_test = data[:split_border,-1]

In [43]:
X_learn[:5]

array([[105, 106, 107, 108],
       [230, 231, 232, 233],
       [ 70,  71,  72,  73],
       [160, 161, 162, 163],
       [425, 426, 427, 428]])