In [1]:
import numpy as np

In [3]:
rand_a=np.random.rand()
rand_a

0.040186261761104625

In [4]:
rand_a=np.random.rand(2,5)
rand_a

array([[0.39300925, 0.07385489, 0.80700343, 0.67686073, 0.27175713],
       [0.50742277, 0.78367592, 0.48189096, 0.42696866, 0.67448568]])

In [6]:
rand_b=np.random.rand(1,5)
rand_b

array([[0.7694302 , 0.08110783, 0.49206927, 0.53682944, 0.77888055]])

In [7]:
rand_b=rand_b*100
rand_b

array([[76.94302002,  8.11078306, 49.20692698, 53.68294394, 77.88805497]])

In [9]:
rand_c=np.vstack([rand_a,rand_b])
rand_c

array([[3.93009254e-01, 7.38548928e-02, 8.07003427e-01, 6.76860728e-01,
        2.71757133e-01],
       [5.07422770e-01, 7.83675917e-01, 4.81890956e-01, 4.26968659e-01,
        6.74485679e-01],
       [7.69430200e+01, 8.11078306e+00, 4.92069270e+01, 5.36829439e+01,
        7.78880550e+01]])

In [10]:
rand_b=np.random.rand(2,1)
rand_b

array([[0.22974256],
       [0.09685554]])

In [11]:
rand_c=np.hstack([rand_a,rand_b])
rand_c

array([[0.39300925, 0.07385489, 0.80700343, 0.67686073, 0.27175713,
        0.22974256],
       [0.50742277, 0.78367592, 0.48189096, 0.42696866, 0.67448568,
        0.09685554]])

In [12]:
X=rand_c[:,1]
X

array([0.07385489, 0.78367592])

In [13]:
a=3
b=8
y=a*X+b
y

array([ 8.22156468, 10.35102775])

In [14]:
X=np.random.randint(low=0,high=10,size=10)
X

array([1, 4, 4, 7, 7, 8, 2, 1, 9, 9])

In [15]:
X=X*10
X

array([10, 40, 40, 70, 70, 80, 20, 10, 90, 90])

In [23]:
np.random.choice(10, size=3, replace=False)

array([6, 5, 7])

In [27]:
np.random.choice(X,size=3,replace=True)

array([20, 20, 90])

In [28]:
idx=np.random.choice(X.shape[0],size=3,replace=False)
X

array([10, 40, 40, 70, 70, 80, 20, 10, 90, 90])

In [29]:
idx

array([9, 4, 5])

In [30]:
X[idx]

array([90, 70, 80])