In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
cols = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS',
        'RAD','TAX','PTRATIO','B','LSTAT','MEDV']

data = pd.read_csv(r"C:\PythonScripts\course-files2\housing.data",
                   sep=' +', engine='python', header=None, 
                   names=cols)

# transforming data - add column with '1' as first column
data['Ones'] = 1

X = data[['Ones']+cols[:-1]].values
print(X)
y = data['MEDV'].values.reshape(-1,1)
print(y)

[[1.0000e+00 6.3200e-03 1.8000e+01 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [1.0000e+00 2.7310e-02 0.0000e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [1.0000e+00 2.7290e-02 0.0000e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [1.0000e+00 6.0760e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0000e+00 1.0959e-01 0.0000e+00 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [1.0000e+00 4.7410e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]
 [15. ]
 [18.9]
 [21.7]
 [20.4]
 [18.2]
 [19.9]
 [23.1]
 [17.5]
 [20.2]
 [18.2]
 [13.6]
 [19.6]
 [15.2]
 [14.5]
 [15.6]
 [13.9]
 [16.6]
 [14.8]
 [18.4]
 [21. ]
 [12.7]
 [14.5]
 [13.2]
 [13.1]
 [13.5]
 [18.9]
 [20. ]
 [21. ]
 [24.7]
 [30.8]
 [34.9]
 [26.6]
 [25.3]
 [24.7]
 [21.2]
 [19.3]
 [20. ]
 [16.6]
 [14.4]
 [19.4]
 [19.7]
 [20.5]
 [25. ]
 [23.4]
 [18.9]
 [35.4]
 [24.7]
 [31.6]
 [23.3]
 [19.6]
 [18.7]
 [16. ]
 [22.2]
 [25. ]
 [33. ]
 [23.5]
 [19.4]
 [22. ]
 [17.4]
 [20

In [5]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

scaler = StandardScaler()
scaler.fit(y)
y = scaler.transform(y)

In [6]:
weights = np.ones((1,X.shape[1])).T/1000
weights

array([[0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001],
       [0.001]])

In [7]:
def predict(X, weights):
        predictions = np.dot(X,weights)
        return predictions.reshape(-1,1)

In [9]:
eta =   0.01 #współczynnik prędkości uczenia się
lmbda =   0.1 #kara L2
epochs = 100 #liczba przebiegów przez dane
N = X.shape[0] #ilość próbek (ilość wierszy w X)

In [10]:
for e in range(epochs):
    
    y_pred = predict(X, weights)
    error_pred = np.sum(np.square(y - y_pred)) + lmbda*np.sum(np.square(weights))    
    delta_weight = np.zeros(weights.shape[0]).reshape(-1,1)    
    
    for j in range(weights.shape[0]):
    
        lin_delta_weights = -2 * np.sum(np.dot(X[:,j], (y - y_pred))) / N
        
        if j ==0:
            weights[j] = weights[j] - eta * lin_delta_weights
        else:
            weights[j] = (1-2*eta*lmbda) * weights[j] - eta * lin_delta_weights 

    print(e, error_pred, np.square(weights).sum())

0 507.9909527546288 0.0010233482561787677
1 455.8944642438375 0.003755558425596725
2 414.4159669467205 0.007653787037955348
3 381.1584539546859 0.012312196967692257
4 354.2796930069831 0.017437833248965456
5 332.3630142628163 0.022821776177750417
6 314.31824652806733 0.028317357367475857
7 299.3057634012569 0.03382374758975061
8 286.67824441562857 0.039273625456407814
9 275.9360160169324 0.04462394209114666
10 266.69280277841233 0.04984903096620102
11 258.6494593262744 0.05493549094500627
12 251.5738206933039 0.059878407222144624
13 245.28524359839537 0.06467857920168163
14 239.64274440163737 0.06934050399655536
15 234.53589491914778 0.07387092497788958
16 229.87783307222477 0.07827780110398543
17 225.59989542040887 0.08256958802037216
18 221.64749366350713 0.086754748751181
19 217.97694537603186 0.09084143219246879
20 214.55303683038704 0.09483727309532257
21 211.34714757939494 0.09874927895702929
22 208.3358061887041 0.10258377811391164
23 205.49957695917007 0.10634641003092307
24 20

In [11]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)

from sklearn.linear_model import Ridge
ridge = Ridge(alpha = lmbda)
ridge.fit(X,y)

Ridge(alpha=0.1)

In [12]:
from sklearn.metrics import r2_score
r2_my_ridge = r2_score(y, predict(X, weights))
r2_lr = r2_score(y, lr.predict(X))
r2_ridge = r2_score(y, ridge.predict(X))

In [13]:
print('R2\t','My Ridge\t', r2_my_ridge, 
      '\tLINREG\t', r2_lr, '\tRIDGE\t', r2_ridge)
print('W \t','My Ridge\t', np.square(weights).sum(), 
      '\tLINREG\t', np.square(lr.coef_).sum(), 
      '\tRIDGE\t', np.square(ridge.coef_).sum())

R2	 My Ridge	 0.7102906376341236 	LINREG	 0.7406426641094093 	RIDGE	 0.7406425368463014
W 	 My Ridge	 0.27316491641279206 	LINREG	 0.6386607850662829 	RIDGE	 0.6373713788702102
