## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [12]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['002', '4.99'],
       ['005', '1.49'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['004', '2.49']], dtype='<U32')

### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [7]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [8]:
A = np.random.randn(10, 8)

np.round(A, 3)

array([[-0.234, -0.234,  1.579,  0.767, -0.469,  0.543, -0.463, -0.466],
       [ 0.242, -1.913, -1.725, -0.562, -1.013,  0.314, -0.908, -1.412],
       [ 1.466, -0.226,  0.068, -1.425, -0.544,  0.111, -1.151,  0.376],
       [-0.601, -0.292, -0.602,  1.852, -0.013, -1.058,  0.823, -1.221],
       [ 0.209, -1.96 , -1.328,  0.197,  0.738,  0.171, -0.116, -0.301],
       [-1.479, -0.72 , -0.461,  1.057,  0.344, -1.763,  0.324, -0.385],
       [-0.677,  0.612,  1.031,  0.931, -0.839, -0.309,  0.331,  0.976],
       [-0.479, -0.186, -1.106, -1.196,  0.813,  1.356, -0.072,  1.004],
       [ 0.362, -0.645,  0.361,  1.538, -0.036,  1.565, -2.62 ,  0.822],
       [ 0.087, -0.299,  0.092, -1.988, -0.22 ,  0.357,  1.478, -0.518]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [13]:
W=np.array([4,5,1])
np.roots(W)

array([-1.  , -0.25])

Dokonaj sprawdzenia.

In [14]:
np.polyval(W, np.roots(W))

array([0., 0.])

### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [20]:
Q = np.array([2,4,-5,1])
R = np.array([2,-5,1])

for name, array in zip(list('QR'), [Q,R]):
  print(f'{name} roots: {array}')

Q roots: [ 2  4 -5  1]
R roots: [ 2 -5  1]


### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [21]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [23]:
np.polyadd(W, Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [24]:
np.polysub(W, Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [25]:
np.polymul(W, Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [27]:
np.polyadd(W, 2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [28]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [30]:
np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [32]:
np.arange('2021-01', '2022-01', dtype='datetime64[M]').reshape(4,-1)

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [35]:
np.datetime64('today')

numpy.datetime64('2022-07-24')