In [2]:
import numpy as np

In [5]:
X = np.arange(1,26).reshape(5,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
Ones = np.ones(X.shape)
Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
X.dot(Ones)

array([[ 15.,  15.,  15.,  15.,  15.],
       [ 40.,  40.,  40.,  40.,  40.],
       [ 65.,  65.,  65.,  65.,  65.],
       [ 90.,  90.,  90.,  90.,  90.],
       [115., 115., 115., 115., 115.]])

In [9]:
diag = np.zeros(X.shape)
diag

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.fill_diagonal(diag,1)
diag

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
X.dot(diag)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [17]:
np.where(X>10,1,0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.where(X%2==0,1,0)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [19]:
np.where(X%2==0,X,X+1)

array([[ 2,  2,  4,  4,  6],
       [ 6,  8,  8, 10, 10],
       [12, 12, 14, 14, 16],
       [16, 18, 18, 20, 20],
       [22, 22, 24, 24, 26]])

In [21]:
X_bis = np.where(X>10,2*X,0)
print(X_bis)
np.count_nonzero(X_bis)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


15

In [22]:
x=np.array([[10,20,30],[40,50,60]])
y=np.array([[100],[200]])
np.append(x,y,axis=1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [23]:
x=np.array([[10,20,30],[40,50,60]])
y=np.array([[100,200,300]])
np.append(x,y,axis=0)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300]])

In [24]:
np.append(x,x,axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])