In [3]:
import numpy as np

In [4]:
X=np.arange(-25,25).reshape(10,5)
X

array([[-25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [13]:
ones=np.ones((np.shape(X)[0],1))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
X_1=np.append(X,ones,axis=1)
X_1

array([[-25., -24., -23., -22., -21.,   1.],
       [-20., -19., -18., -17., -16.,   1.],
       [-15., -14., -13., -12., -11.,   1.],
       [-10.,  -9.,  -8.,  -7.,  -6.,   1.],
       [ -5.,  -4.,  -3.,  -2.,  -1.,   1.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.]])

In [22]:
w=np.random.rand(np.shape(X_1)[1])
w

array([0.80675839, 0.96683186, 0.20660704, 0.49673203, 0.30100063,
       0.30294778])

In [19]:
def predict(x,w):
    total_stimulation=np.dot(x,w)
    if total_stimulation>=0:
        return 1
    else:
        return -1

In [23]:
print(predict(X_1[0,],w))

-1


In [25]:
for x in X_1:
    print(predict(x,w))

-1
-1
-1
-1
-1
1
1
1
1
1
