In [1]:
    import numpy as np
     
    data = np.array([[10, 7, 4], [3, 2, 1]])
    data

array([[10,  7,  4],
       [ 3,  2,  1]])

In [2]:
np.mean(data)

4.5

In [3]:
np.mean(data, axis=0)

array([6.5, 4.5, 2.5])

In [4]:
np.mean(data, axis=1)

array([7., 2.])

In [5]:
np.average(data)

4.5

In [6]:
np.average(data, axis=0)

array([6.5, 4.5, 2.5])

In [7]:
np.average(data, axis=1)

array([7., 2.])

In [9]:
np.average(data, axis=1, weights=[0,1,1])

array([5.5, 1.5])

In [10]:
np.average(data, axis=1, weights=[2,3,5])

array([6.1, 1.7])

In [11]:
np.var(data)

9.583333333333334

In [12]:
np.var(data, axis=0)

array([12.25,  6.25,  2.25])

In [13]:
np.var(data, axis=1)

array([6.        , 0.66666667])

In [14]:
np.std(data)

3.095695936834452

In [15]:
np.std(data, axis=0)

array([3.5, 2.5, 1.5])

In [16]:
np.std(data, axis=1)

array([2.44948974, 0.81649658])

In [18]:
    data = np.zeros((2, 1000000))
    data[0, :] = 1.0
    data[1, :] = 0.1
    print(np.mean(data, dtype=np.float32))
    print(np.mean(data, dtype=np.float64))

0.55000126
0.5499999999999972


In [20]:
    data = np.zeros((2, 10))
    data[0, :] = 1.0
    data[1, :] = 0.1
    print(np.mean(data, dtype=np.float32))
    print(np.mean(data, dtype=np.float64))

0.5500001
0.55
