In [1]:
    import numpy as np
    import pandas as pd
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import Perceptron

In [4]:
df=pd.read_csv(r'C:\PythonScripts\course-files2\breast_cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [7]:
X=df[['area_mean','area_se','texture_mean','concavity_worst','concavity_mean']].values
X[:10]

array([[1.001e+03, 1.534e+02, 1.038e+01, 7.119e-01, 3.001e-01],
       [1.326e+03, 7.408e+01, 1.777e+01, 2.416e-01, 8.690e-02],
       [1.203e+03, 9.403e+01, 2.125e+01, 4.504e-01, 1.974e-01],
       [3.861e+02, 2.723e+01, 2.038e+01, 6.869e-01, 2.414e-01],
       [1.297e+03, 9.444e+01, 1.434e+01, 4.000e-01, 1.980e-01],
       [4.771e+02, 2.719e+01, 1.570e+01, 5.355e-01, 1.578e-01],
       [1.040e+03, 5.391e+01, 1.998e+01, 3.784e-01, 1.127e-01],
       [5.779e+02, 5.096e+01, 2.083e+01, 2.678e-01, 9.366e-02],
       [5.198e+02, 2.432e+01, 2.182e+01, 5.390e-01, 1.859e-01],
       [4.759e+02, 2.394e+01, 2.404e+01, 1.105e+00, 2.273e-01]])

In [15]:
y=df['diagnosis'].apply(lambda x: 1 if x=='M' else 0)
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [17]:
scaler=StandardScaler()
scaler.fit(X)
X_std=scaler.transform(X)
X_std

array([[ 0.9843749 ,  2.48757756, -2.07333501,  2.10952635,  2.65287398],
       [ 1.90870825,  0.74240195, -0.35363241, -0.14674897, -0.02384586],
       [ 1.55888363,  1.18133606,  0.45618695,  0.85497394,  1.36347845],
       ...,
       [ 0.57795264,  0.1806983 ,  2.0455738 ,  0.3267666 ,  0.04658753],
       [ 1.73521799,  1.0095027 ,  2.33645719,  3.19760468,  3.296944  ],
       [-1.34778924, -0.46615196,  1.22179204, -1.30583065, -1.11487284]])

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.2)

In [27]:
perceptron=Perceptron(eta0=0.01, max_iter=100)
perceptron.fit(X_train, y_train)

Perceptron(eta0=0.01, max_iter=100)

In [28]:
y_pred=perceptron.predict(X_test)
y_pred

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1], dtype=int64)

In [29]:
good_results = [(a,b) for (a,b) in zip(y_pred[y_pred==y_test], y_test[y_pred==y_test])]
len(good_results)

108

In [30]:
bad_results = [(a,b) for (a,b) in zip(y_pred[y_pred!=y_test], y_test[y_pred!=y_test])]
len(bad_results)

6

In [31]:
print(len(good_results)/len(y_test))

0.9473684210526315
